const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/data/bridge-profile-schema.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('app/src/main/assets/data/bridge-checklists.js','utf8'),ctx);
const fieldId=label=>ctx.BRIDGE_PROFILE_SCHEMA.sections.flatMap(s=>s.fields).find(f=>f.label===label).id;
const sectionField=(sectionId,label)=>ctx.BRIDGE_PROFILE_SCHEMA.sections.find(s=>s.id===sectionId).fields.find(f=>f.label===label).id;
const make=(use,material,pavement)=>({profile:{[fieldId('نام پل')]:'پل آزمایشی',[fieldId('کاربری اصلی')]:use,[fieldId('مصالح اَبَرسازه')]:material,[fieldId('نوع روسازی')]:pavement}});
const road=ctx.checklistsForBridge(make('راه','بتن درجا - بتن مسلح','آسفالت'));
const rail=ctx.checklistsForBridge(make('راه‌آهن','فولادی','راه‌آهن - ریل روی تراورس و بالاست متکی بر عرشه'));
const roadIds=new Set(road.map(x=>x.id)),railIds=new Set(rail.map(x=>x.id));
assert(roadIds.has('road_pavement'));assert([...roadIds].some(id=>id.startsWith('concrete--05_')));assert(!roadIds.has('rail'));
assert(!road.find(x=>x.id==='road_pavement').items.some(x=>x.name.includes('روسازی بتنی')));
for(const id of ['rail','rail_weld','rail_fasteners','rail_ballast','rail_geometry','rail_safety'])assert(railIds.has(id),id);
assert([...railIds].some(id=>id.startsWith('steel--05_')));
assert(!railIds.has('road_pavement'));
const direct=ctx.checklistsForBridge(make('راه‌آهن','فولادی','راه‌آهن - ریل مستقیم بر عناصر کف عرشه'));
assert(!direct.some(x=>x.id==='rail_ballast'));
assert(direct.find(x=>x.id==='rail_fasteners').items.some(x=>x.name.includes('بست مستقیم')));
assert(!direct.find(x=>x.id==='rail_fasteners').items.some(x=>x.name.includes('تراورس')));
const noBarrier=make('راه‌آهن','فولادی','راه‌آهن - ریل مستقیم بر عناصر کف عرشه');
noBarrier.profile[sectionField('14_نرده_جانپناه','وجود جزء؟')]='وجود ندارد';
noBarrier.profile[sectionField('15_پیاده_رو_جزیره','وجود پیاده‌رو/جزیره؟')]='وجود ندارد';
assert(!ctx.checklistsForBridge(noBarrier).find(x=>x.id==='rail_safety').items.some(x=>/نرده|حفاظ سقوط/.test(x.name)));
const nonCable=make('راه','بتن درجا - بتن مسلح','آسفالت');
nonCable.profile[sectionField('18_کابل_دیافراگم','وجود سیستم ویژه؟')]='وجود ندارد';
nonCable.profile[sectionField('18_کابل_دیافراگم','کابل/سیستم اصلی')]='فاقد کابل اصلی';
nonCable.profile[fieldId('نوع سیستم عرشه')]='پل کابلی - جعبه‌ای درجای پیش‌تنیده';
nonCable.profile[fieldId('سیستم سازه‌ای اصلی')]='ترکه‌ای (کابلی) - بادبزنی';
assert(!ctx.bridgeProfileTags(nonCable).has('cable'));assert(!ctx.checklistsForBridge(nonCable).some(x=>x.id==='cable'));
assert.strictEqual(ctx.bridgeProfileValue(nonCable,'نوع سیستم عرشه'),'');
assert.strictEqual(ctx.bridgeProfileValue(nonCable,'سیستم سازه‌ای اصلی'),'');
const neoprene=make('راه','بتن درجا - بتن مسلح','آسفالت');
neoprene.profile[sectionField('10_تکیه_گاه','وجود دستگاه تکیه‌گاهی؟')]='وجود دارد';
neoprene.profile[sectionField('10_تکیه_گاه','نوع تکیه‌گاه اصلی')]='الاستومر';
neoprene.profile[sectionField('10_تکیه_گاه','مصالح/زیرنوع تکیه‌گاه')]='لاستیک مصنوعی (نئوپرن/کلرو/بوتیل)';
const neopreneChecklist=ctx.checklistsForBridge(neoprene),neopreneCategory=neopreneChecklist.find(x=>x.id==='neoprene');
assert(neopreneCategory&&neopreneCategory.items.some(x=>x.name==='جداشدگی لایه‌های لاستیک از ورق تقویتی'));
const concreteCatalog=ctx.BRIDGE_CHECKLIST_CATALOG.find(x=>x.id==='concrete').items.map(x=>x.name);
for(const defect of ['پوسته‌شدن سطح بتن','ورقه‌شدن بتن','قلوه‌کن‌شدن بتن','کرموشدگی بتن'])assert(concreteCatalog.includes(defect),defect);
assert(ctx.BRIDGE_CHECKLIST_CATALOG.find(x=>x.id==='concrete').items.every(x=>x.id.startsWith('v12-concrete-')));
const legacyConcrete=ctx.bridgeLegacyChecklistDefinition('concrete-6--05_عرشه_ابرسازه');
assert.strictEqual(legacyConcrete.item,'پوسته‌شدن، ورقه‌شدن، طبله‌کردن یا جداشدگی پوشش بتن');
assert(legacyConcrete.category.includes('عرشه و اَبَرسازه'));
assert.strictEqual(ctx.bridgeLegacyChecklistDefinition('v12-concrete-6--05_عرشه_ابرسازه'),null);
const unknown=make('راه','','');
assert(!ctx.checklistsForBridge(unknown).some(x=>/^(concrete|steel|masonry|timber|composite|prestress)--/.test(x.id)));
assert(rail.flatMap(c=>c.items).length>90);assert(road.flatMap(c=>c.items).length>60);
assert(ctx.BRIDGE_CHECKLIST_CATALOG.length>=35);assert(ctx.BRIDGE_CHECKLIST_CATALOG.flatMap(c=>c.items).length>=350);
assert(road.every(c=>c.items.every(i=>/^\d+\.\d+$/.test(i.code))));
assert(Object.keys(ctx.BRIDGE_ENGINEERING_REFERENCES).length>=6);
console.log('dynamic_checklist.test.js PASS');
