const fs=require('fs'),vm=require('vm'),assert=require('assert');
global.window=global;
global.faNum=x=>String(x);
global.esc=x=>String(x);
global.CSS={escape:x=>String(x)};
let toastMsg='';global.toast=m=>{toastMsg=m};
let textNode={textContent:''},host={classList:{add(){},remove(){}},querySelector(sel){return sel==='.occ-location-text'?textNode:null}};
global.document={querySelector(){return host}};
global.Native={isNative(){return true},requestLocation(){return true}};
global.currentInspection={id:'visit-1',itemLocations:{}};
vm.runInThisContext(fs.readFileSync('app/src/main/assets/js/locations.js','utf8'));
let l=normalizeOccurrenceLocation({lat:'35.6892',lon:'51.3890',accuracyM:'7.4',capturedAt:123,provider:'gps'});
assert.strictEqual(l.lat,35.6892);assert.strictEqual(l.lon,51.389);assert.strictEqual(l.accuracyM,7.4);assert.strictEqual(l.provider,'gps');
assert.strictEqual(normalizeOccurrenceLocation({lat:91,lon:1}),null);
captureOccurrenceLocation('bridge-1::1');
receiveLocationResult({ok:true,target:'bridge-1::1',lat:35.7,lon:51.4,accuracyM:8,capturedAt:Date.now(),mock:true});
assert.strictEqual(currentInspection.itemLocations['bridge-1::1'],undefined);assert(toastMsg.includes('موقعیت واقعی'));
captureOccurrenceLocation('bridge-1::1');
receiveLocationResult({ok:true,target:'bridge-1::1',lat:35.7,lon:51.4,accuracyM:8,capturedAt:Date.now()-180000,mock:false});
assert.strictEqual(currentInspection.itemLocations['bridge-1::1'],undefined);assert(toastMsg.includes('قدیمی'));
captureOccurrenceLocation('bridge-1::1');
receiveLocationResult({ok:true,target:'bridge-1::1',lat:35.7,lon:51.4,accuracyM:8,capturedAt:Date.now(),provider:'gps',mock:false});
assert.strictEqual(currentInspection.itemLocations['bridge-1::1'].lat,35.7);assert.strictEqual(currentInspection.itemLocations['bridge-1::1'].lon,51.4);
clearOccurrenceLocation('bridge-1::1');assert.strictEqual(currentInspection.itemLocations['bridge-1::1'],null);
assert.strictEqual(occurrenceLocationFor('bridge-1::1',{lat:35,lon:51}),null);
console.log('location.test.js PASS');
