const fs=require('fs'),assert=require('assert');
const core=fs.readFileSync('app/src/main/assets/js/app-core.js','utf8');
const reports=fs.readFileSync('app/src/main/assets/js/reports.js','utf8');
const html=fs.readFileSync('app/src/main/assets/index.html','utf8');
const gestures=fs.readFileSync('app/src/main/assets/js/gestures.js','utf8');
const reportJava=fs.readFileSync('app/src/main/java/ir/bridge/maintenance/ReportExporter.java','utf8');
assert(core.includes('function occurrenceCode'));
assert(core.includes('function addChecklistOccurrence'));
assert(!core.includes('occ-km-start')&&!core.includes('occ-km-end'));
assert(core.includes('occurrenceIndex')&&core.includes('data-photo-key'));
assert(reports.includes("makeZIP")&&reports.includes('exportHistoryZip'));
assert(html.includes("exportReport('zip')")&&html.includes('ZIP سوابق'));
assert(core.includes('sortedChecklistCategories')&&core.includes('compareChecklistCodes'));
assert(core.includes('checkcat collapsed')&&core.includes('toggleChecklistCategory')&&core.includes('checkcat-body'));
assert(reports.includes('severitySort')&&reports.includes('compareCodes(itemOccurrenceCode(a), itemOccurrenceCode(b))'));
assert(gestures.includes("touchstart")&&gestures.includes("touchmove")&&gestures.includes("openDrawer('left')")&&gestures.includes("openDrawer('right')"));
assert(reportJava.includes('measureRtlHeight')&&reportJava.includes('xlsxStyles')&&reportJava.includes('xl/worksheets/sheet3.xml'));
assert(!reportJava.includes('"GPS پل"')&&!reportJava.includes('"اقدام / مسئول"'));
assert(reportJava.includes('ReportLayout.writePdf'));
assert(reportJava.includes('sanitizeChecklistRows')&&reportJava.includes('isChecklistMetadataHeader')&&reportJava.includes('تاریخ'));
for(const header of ['نام پل','کد پل','کاربری پل','نوع بازدید'])assert(reports.includes(header));
assert(reportJava.includes('data/bridges.json')&&reportJava.includes('bridge-inspection-report.csv'));
console.log('occurrence_export.test.js PASS');
