const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('app/src/main/assets/index.html','utf8');
const core=fs.readFileSync('app/src/main/assets/js/app-core.js','utf8');
const css=fs.readFileSync('app/src/main/assets/css/app.css','utf8');
const media=fs.readFileSync('app/src/main/java/ir/bridge/maintenance/AppMediaStore.java','utf8');
const exporter=fs.readFileSync('app/src/main/java/ir/bridge/maintenance/ReportExporter.java','utf8');
assert(!html.includes('id="axis"')&&!html.includes('id="block"')&&!html.includes('id="lat"')&&!html.includes('id="lng"'));
for(const removed of ['region','fromStation','toStation','lineType','locationType','kmStart','kmEnd','kmDir','speed','lineClass','weather'])assert(!html.includes(`id="${removed}"`),removed);
assert(html.includes('id="bridges"')&&html.includes('id="bridgeForm"')&&html.includes('id="inspectionBridge"'));
assert(core.includes('function saveUserEditor')&&core.includes("dbSave('users'"));
assert(core.includes('function saveSignature')&&core.includes('signatureAttachment'));
assert(media.includes('saveSignatureDataUri')&&media.includes('Signatures'));
assert(exporter.includes('امضا/')&&exporter.includes('signatureAttachment'));
assert(html.includes('id="guide"')&&html.includes('راهنمای استفاده')&&html.includes('ثبت GPS'));
for(const c of ['selected.sev-normal','selected.sev-mild','selected.sev-medium','selected.sev-critical'])assert(css.includes(c));
assert(!html.includes('go(\'assets\')')&&!html.includes('go(\'network\')'));
assert(html.includes('شرکت مهندسین مشاور هگزا'));
assert(html.includes('Powered By Daniyal Salimi')&&html.includes('id="inspectorName"'));
assert(css.includes('veresk_loading.jpg')&&css.includes('.marquee-text.is-overflowing'));
assert(css.includes('body[data-theme="night"]')&&css.includes('placeholder'));
console.log('ui_integrity.test.js PASS');
